name: ci-kv-storage-contract

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  ci-smart-contract:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy
      # Needed for gcc install
      - run: sudo apt update && sudo apt install -y build-essential wabt
      - uses: Swatinem/rust-cache@v1
      - run: make prepare
      # - run: make check-lint
      - run: make test
      - uses: actions/upload-artifact@v3
        with:
          name: contract.wasm
          path: target/wasm32-unknown-unknown/release/contract.wasm